### ISSUE TITLE
Error disconnecting the bot

### ISSUE THREAD

**Issue by Sequelado** [LeonZ2019/dbm-discord.js-v12#1]
I was testing this version v12 and an error happened to me, when disconnecting the bot from the voice channel, the bot is turned off (sorry for english)

![error](https://user-images.githubusercontent.com/47487536/80523690-d6b2d300-8964-11ea-8564-0c7bc7bc2629.gif)
![Screenshot_1](https://user-images.githubusercontent.com/47487536/80523744-f1854780-8964-11ea-99a4-7756cdf2ed06.png)

**Comment by LeonZ2019** [comment]
Ok, i will fix this problem asap

**Comment by LeonZ2019** [comment]
this issue has fixed now, get 1.1.3 from release https://github.com/LeonZ2019/dbm-discord.js-v12/releases/tag/1.1.3
